FROM --platform=linux/amd64 ubuntu:22.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential git curl libz-dev

COPY . /repo
WORKDIR /repo
RUN make -j8 release

FROM ubuntu:22.04 as package
COPY --from=builder /repo/stringtie /
